### Vectorization

In [2]:
import numpy as np
import time 

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorized version: {0} ms".format(str(1000*(toc-tic))))

c = 0
tic = time.time()

for i in range(1000000):
    c+=a[i]*b[i]
    
toc = time.time()

print("For loop version: {0} ms".format(str(1000*(toc-tic))))


Vectorized version: 0.9717941284179688 ms
For loop version: 478.0383110046387 ms


### Broadcasting


In [10]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [11]:
cal = A.sum(axis = 0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [14]:
percentage = 100*A/cal.reshape(1, 4)

In [15]:
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [21]:
a = np.random.randn(12288, 150)
b = np.random.randn(150, 45)
print(a)
print(b)
c = np.dot(a, b)
c.shape

[[-0.53782015 -0.69505151 -0.62177777 ... -0.53256204 -1.05836972
  -0.21965485]
 [ 0.24153034  1.39799069 -1.10647162 ...  0.35598672  0.46519284
   1.44279032]
 [-0.80288546 -0.2256073   0.04306516 ... -1.62985308  2.53494639
   0.14516817]
 ...
 [ 0.6740916   0.26830449  0.94866451 ... -0.34606571  1.22464703
   1.71185701]
 [-0.75608231 -0.94511832  0.26933687 ... -2.21263744  0.99039964
   0.99033076]
 [-0.51834384  1.03874641 -1.19977448 ... -0.1567949  -0.46338638
   0.453581  ]]
[[-1.14558362 -0.88460885  1.50526877 ... -0.25647761 -1.76646559
  -1.43608461]
 [-0.32907045  0.23407564 -0.18107407 ...  0.34369973 -0.10779666
  -0.98067496]
 [-0.71882062  1.60278301  1.08769121 ...  1.10011498  0.07919473
   1.34399417]
 ...
 [ 2.20755303 -0.64070415  1.90942083 ... -1.3976545  -0.38964883
   0.97217103]
 [-0.03975188 -0.32068296 -0.02973411 ...  0.91252297 -0.8533032
   0.86253679]
 [ 0.05517075 -0.1010163   2.09105782 ...  1.16495017 -0.39721052
  -0.8880723 ]]


(12288, 45)

In [23]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
print(a)
print(b)
c = a*b
c

[[ 0.15824423 -0.35592226 -1.07793035]
 [ 2.4553467  -1.04004128 -0.16708604]
 [-1.0538755   1.28950438 -0.01034349]]
[[-0.2381374 ]
 [-0.48977655]
 [-0.01700773]]


array([[-3.76838702e-02,  8.47584016e-02,  2.56695533e-01],
       [-1.20257123e+00,  5.09387829e-01,  8.18348231e-02],
       [ 1.79240320e-02, -2.19315450e-02,  1.75919245e-04]])